{{- if .Values.serviceAccount.controller.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "btrfs-nfs-csi.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "btrfs-nfs-csi.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.controller.automount }}
{{- end }}
