{{- if .Values.serviceAccount.driver.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "btrfs-nfs-csi.driverServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "btrfs-nfs-csi.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.driver.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.driver.automount }}
{{- end }}
