package v1

// Token verification for AGENT_TENANTS entries.
//
// Each entry stores either a plaintext token (back-compat) or a password
// hash in PHC string format. Hashes start with `$`; anything else is
// plaintext. Supported hash schemes:
//
//   - bcrypt: $2a$ / $2b$ / $2y$ -- generated by `htpasswd -nbB '' <secret> | cut -c2-`
//
// Argon2id (`$argon2id$...`) is rejected: its PHC params include commas
// (e.g. `m=65536,t=3,p=4`) which collide with the AGENT_TENANTS entry
// separator.
//
// Hot path: a fingerprint cache short-circuits the slow bcrypt verify so
// repeated requests with the same token cost only one HMAC-SHA256 plus a
// map lookup. Cache keys are HMAC fingerprints of the *provided* token,
// salted with the per-installation root secret -- attackers cannot forge
// keys.

import (
	"crypto/subtle"
	"errors"
	"fmt"
	"strings"
	"sync"

	"github.com/erikmagkekse/btrfs-nfs-csi/agent/api/v1/models"
	"golang.org/x/crypto/bcrypt"
)

// TokenCredential is one parsed AGENT_TENANTS entry handed to NewTokenSet.
type TokenCredential struct {
	Stored string // plaintext token or PHC hash string
	Info   models.TenantInfo
}

// TokenEntry is the credential-free projection returned by Tokens.Entries.
type TokenEntry struct {
	Info        models.TenantInfo
	Fingerprint string
}

// TokenSet holds every configured tenant credential and verifies bearer
// tokens against them. Safe for concurrent use after construction.
type TokenSet struct {
	entries []*tokenInternal
	fp      func(string) string // stable non-reversible fingerprint; secret.Manager.Fingerprint in production
	cache   sync.Map            // fp(provided) -> *tokenInternal
}

type tokenInternal struct {
	info        models.TenantInfo
	fingerprint string // fp(stored) -- stable for audit; cached at construction
	plaintext   string // set for plaintext entries
	bcryptHash  []byte // set for bcrypt entries
}

// NewTokenSet builds a TokenSet from creds. Duplicates (same Stored value)
// are rejected. fingerprint is used for cache keys and audit fingerprints;
// pass nil only in tests where the cache and fingerprint output are not
// exercised.
func NewTokenSet(creds []TokenCredential, fingerprint func(string) string) (*TokenSet, error) {
	ts := &TokenSet{fp: fingerprint}
	seen := make(map[string]string, len(creds))
	for _, cr := range creds {
		if dup, ok := seen[cr.Stored]; ok {
			return nil, fmt.Errorf("duplicate credential shared by tenants %q and %q", dup, cr.Info.Name)
		}
		seen[cr.Stored] = cr.Info.Name

		e, err := parseTokenEntry(cr.Stored, cr.Info)
		if err != nil {
			return nil, fmt.Errorf("tenant %q: %w", cr.Info.Name, err)
		}
		if fingerprint != nil {
			e.fingerprint = fingerprint(cr.Stored)
		}
		ts.entries = append(ts.entries, e)

		// Pre-warm the cache for plaintext entries: their fp(stored) equals
		// the fp(provided) for any matching request, so we skip the slow
		// path on first use too.
		if e.plaintext != "" && fingerprint != nil {
			ts.cache.Store(e.fingerprint, e)
		}
	}
	return ts, nil
}

// bcryptPrefixes are the PHC identifiers we accept as bcrypt. All three
// denote the same algorithm; the marker only records which implementation
// produced the hash. Go's bcrypt verifies all of them identically.
var bcryptPrefixes = []string{"$2a$", "$2b$", "$2y$"}

func parseTokenEntry(stored string, info models.TenantInfo) (*tokenInternal, error) {
	if stored == "" {
		return nil, errors.New("empty credential")
	}
	for _, p := range bcryptPrefixes {
		if strings.HasPrefix(stored, p) {
			// Fail fast at boot rather than on every request.
			if _, err := bcrypt.Cost([]byte(stored)); err != nil {
				return nil, fmt.Errorf("invalid bcrypt hash: %w", err)
			}
			return &tokenInternal{info: info, bcryptHash: []byte(stored)}, nil
		}
	}
	if strings.HasPrefix(stored, "$") {
		return nil, fmt.Errorf("unsupported hash scheme %q (supported: bcrypt $2a$/$2b$/$2y$)", schemeOf(stored))
	}
	return &tokenInternal{info: info, plaintext: stored}, nil
}

// schemeOf returns the leading "$id$" segment of a PHC string for error reporting.
func schemeOf(s string) string {
	if len(s) < 2 || s[0] != '$' {
		return s
	}
	if i := strings.IndexByte(s[1:], '$'); i > 0 {
		return s[:i+2]
	}
	return s
}

// Verify returns the matched tenant info and stable fingerprint, or ok=false
// for unknown tokens. Constant-time per entry; the fingerprint cache makes
// repeat lookups cheap even with bcrypt entries.
func (ts *TokenSet) Verify(provided string) (models.TenantInfo, string, bool) {
	if ts == nil || provided == "" || len(ts.entries) == 0 {
		return models.TenantInfo{}, "", false
	}
	var fpProvided string
	if ts.fp != nil {
		fpProvided = ts.fp(provided)
		if v, ok := ts.cache.Load(fpProvided); ok {
			e := v.(*tokenInternal)
			return e.info, e.fingerprint, true
		}
	}
	provBytes := []byte(provided)
	for _, e := range ts.entries {
		if matchToken(e, provBytes) {
			if ts.fp != nil {
				ts.cache.Store(fpProvided, e)
			}
			return e.info, e.fingerprint, true
		}
	}
	return models.TenantInfo{}, "", false
}

func matchToken(e *tokenInternal, provided []byte) bool {
	if e.plaintext != "" {
		return subtle.ConstantTimeCompare([]byte(e.plaintext), provided) == 1
	}
	if len(e.bcryptHash) > 0 {
		return bcrypt.CompareHashAndPassword(e.bcryptHash, provided) == nil
	}
	return false
}

// Entries returns a credential-free projection. Order matches construction.
func (ts *TokenSet) Entries() []TokenEntry {
	if ts == nil {
		return nil
	}
	out := make([]TokenEntry, len(ts.entries))
	for i, e := range ts.entries {
		out[i] = TokenEntry{Info: e.info, Fingerprint: e.fingerprint}
	}
	return out
}

// FilterTenant returns only entries whose Info.Name matches.
func (ts *TokenSet) FilterTenant(tenant string) []TokenEntry {
	if ts == nil {
		return nil
	}
	out := make([]TokenEntry, 0)
	for _, e := range ts.entries {
		if e.info.Name == tenant {
			out = append(out, TokenEntry{Info: e.info, Fingerprint: e.fingerprint})
		}
	}
	return out
}

// Len reports the number of configured entries.
func (ts *TokenSet) Len() int {
	if ts == nil {
		return 0
	}
	return len(ts.entries)
}
