apiVersion: v2
name: btrfs-nfs-csi
description: Kubernetes CSI driver that turns any btrfs filesystem into a full-featured NFS storage backend with instant snapshots, clones, and quotas
type: application
version: 0.1.1
appVersion: "0.9.11"
kubeVersion: ">=1.30.0-0"
home: https://github.com/erikmagkekse/btrfs-nfs-csi
sources:
  - https://github.com/erikmagkekse/btrfs-nfs-csi
keywords:
  - csi
  - btrfs
  - nfs
  - storage
  - snapshots
maintainers:
  - name: erikmagkekse
    email: me@eriks.life
    url: https://github.com/erikmagkekse
